### ISSUE TITLE
How to debug please?

### ISSUE THREAD

**Issue by SageKatalyst** [exzyyywakeup/Apex-NoRecoil-2023#1]
I downloaded this package, delete the ahk install folder and used that gui.ahk everything seemed to be okay. I clicked the 'save and run' and it said it was working but there's no effect in apex.
![微信截图_20230903085718](https://github.com/exzyyywakeup/Apex-NoRecoil-2023/assets/142864511/513d67cb-e1b3-48d1-a919-48a6502d67dc)

**Comment by exzyyywakeup** [comment]
so you chosen customized resolutions to make it work you need to create it yourself

https://www.youtube.com/watch?v=VhpEi4_U3lc
