### ISSUE TITLE
There is a bug! ! !

### ISSUE THREAD

**Issue by sjiebn** [exzyyywakeup/Apex-NoRecoil-2023#17]
When using the runaway light machine gun, you can't shoot repeatedly, and after charging, you will inexplicably start using large batteries.

**Comment by XuBoZhangQvQ** [comment]
我也碰到了这个问题，
在使用暴走并且充能的时候，
背包里面存在凤凰治疗包的时候，点击鼠标，会拿出凤凰
具体代码在这里

        global Subshootkey := 9
        If (RapidMode) {
            If A_Index < 3
                Click
            Else
                Random, Rand, 1, 2
            If(Rand = 1)
                Click
            Else
                Send % Subshootkey
        }

**Comment by XuBoZhangQvQ** [comment]
![image](https://github.com/exzyyywakeup/Apex-NoRecoil-2023/assets/35949334/75c34b3a-1891-42c9-9649-c47b0142b2d3)
可以把凤凰治疗包的9快捷键，解除绑定
