### ISSUE TITLE
It seems that some weapons fire automatically with Phoenix

### ISSUE THREAD

**Issue by taiyisama** [exzyyywakeup/Apex-NoRecoil-2023#3]

**Comment by exzyyywakeup** [comment]
![image](https://github.com/exzyyywakeup/Apex-NoRecoil-2023/assets/80401543/46cc8e36-5adb-4b79-bbce-47e6af1b3034)
attack key 9

**Comment by taiyisama** [comment]
This came out of nowhere. I haven't seen it since I went to the shooting range

**Comment by taiyisama** [comment]
Some guns will be fully automatic when I turn off a single shot, such as the g7 and Hemlock
