### ISSUE TITLE
How to close autofire?it is always open.

### ISSUE THREAD

**Issue by YNFoEver** [exzyyywakeup/Apex-NoRecoil-2023#5]
How to close autofire,it is always open

**Comment by exzyyywakeup** [comment]
replace apexmaster.ahk (not tested may be buggy)
[apexmaster.zip](https://github.com/exzyyywakeup/Apex-NoRecoil-2023/files/13226939/apexmaster.zip)

**Comment by YNFoEver** [comment]
Thank you, but this still doesn't seem to be useful

**Comment by YNFoEver** [comment]
> replace apexmaster.ahk (not tested may be buggy) [apexmaster.zip](https://github.com/exzyyywakeup/Apex-NoRecoil-2023/files/13226939/apexmaster.zip)

Thank you, but this still doesn't seem to be useful

**Comment by exzyyywakeup** [comment]
why

**Comment by YNFoEver** [comment]
I don't know why. Have you ever used Apex-NoRecoil-2021? He can choose whether to open autofire in the gui file, and I thought maybe we could look into that, which is also in github.发自我的荣耀手机-------- 原始邮件 --------发件人： exzyyy ***@***.***>日期： 2023年11月3日周五 凌晨3:13收件人： exzyyywakeup/Apex-NoRecoil-2023 ***@***.***>抄送： YNFoEver ***@***.***>, Author ***@***.***>主    题： Re: [exzyyywakeup/Apex-NoRecoil-2023] How to close autofire?it is always open. (Issue #5)
why

**Comment by exzyyywakeup** [comment]
maybe in future
