### ISSUE TITLE
Hello, please update R99 recoil, S20 R99 recoil has changed, thank you very much!

### ISSUE THREAD

**Issue by jyq694966497** [exzyyywakeup/Apex-NoRecoil-2023#9]
Hello, please update R99 recoil, S20 R99 recoil has changed, thank you very much!

**Comment by exzyyywakeup** [comment]
Updated please redownload
not as perfect as it could be but its better

**Comment by jyq694966497** [comment]
> 更新，请重新下载，虽然不那么完美，但更好

thank you very much!
